from enum import Enum


class BoardColors(Enum):
    belize = "belize"
    nephritis = "nephritis"
    pomegranate = "pomegranate"
    pumpkin = "pumpkin"
    wisteria = "wisteria"
    moderatepink = "moderatepink"
    strongcyan = "strongcyan"
    limegreen = "limegreen"
    midnight = "midnight"
    dark = "dark"
    relax = "relax"
    corteza = "corteza"


class Colors(Enum):
    white = "white"
    green = "green"
    yellow = "yellow"
    orange = "orange"
    red = "red"
    purple = "purple"
    blue = "blue"
    sky = "sky"
    lime = "lime"
    pink = "pink"
    black = "black"
    silver = "silver"
    peachpuff = "peachpuff"
    crimson = "crimson"
    plum = "plum"
    darkgreen = "darkgreen"
    slateblue = "slateblue"
    magenta = "magenta"
    gold = "gold"
    navy = "navy"
    gray = "gray"
    saddlebrown = "saddlebrown"
    paleturquoise = "paleturquoise"
    mistyrose = "mistyrose"
    indigo = "indigo"
